[2024-07-25T17:53:36.023+0000] {processor.py:161} INFO - Started process (PID=31) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T17:53:36.024+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T17:53:36.026+0000] {logging_mixin.py:188} INFO - [2024-07-25T17:53:36.026+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T17:53:36.034+0000] {logging_mixin.py:188} INFO - [2024-07-25T17:53:36.032+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/great_expectations_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_dag.py", line 4, in <module>
    from great_expectations_provider.operators.great_expectations import GreatExpectationsOperator
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-07-25T17:53:36.035+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T17:53:36.053+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 0.035 seconds
[2024-07-25T17:54:06.816+0000] {processor.py:161} INFO - Started process (PID=90) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T17:54:06.817+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T17:54:06.820+0000] {logging_mixin.py:188} INFO - [2024-07-25T17:54:06.820+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T17:54:06.826+0000] {logging_mixin.py:188} INFO - [2024-07-25T17:54:06.825+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/great_expectations_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_dag.py", line 4, in <module>
    from great_expectations_provider.operators.great_expectations import GreatExpectationsOperator
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-07-25T17:54:06.827+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T17:54:06.842+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 0.033 seconds
[2024-07-25T17:54:43.365+0000] {processor.py:161} INFO - Started process (PID=149) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T17:54:43.475+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T17:54:43.566+0000] {logging_mixin.py:188} INFO - [2024-07-25T17:54:43.566+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T17:54:43.702+0000] {logging_mixin.py:188} INFO - [2024-07-25T17:54:43.677+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/great_expectations_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_dag.py", line 4, in <module>
    from great_expectations_provider.operators.great_expectations import GreatExpectationsOperator
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-07-25T17:54:43.710+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T17:54:43.799+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 0.455 seconds
[2024-07-25T17:55:14.581+0000] {processor.py:161} INFO - Started process (PID=209) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T17:55:14.582+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T17:55:14.585+0000] {logging_mixin.py:188} INFO - [2024-07-25T17:55:14.585+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T17:55:14.590+0000] {logging_mixin.py:188} INFO - [2024-07-25T17:55:14.589+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/great_expectations_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_dag.py", line 4, in <module>
    from great_expectations_provider.operators.great_expectations import GreatExpectationsOperator
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-07-25T17:55:14.591+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T17:55:14.606+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 0.033 seconds
[2024-07-25T17:55:45.387+0000] {processor.py:161} INFO - Started process (PID=269) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T17:55:45.388+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T17:55:45.389+0000] {logging_mixin.py:188} INFO - [2024-07-25T17:55:45.389+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T17:55:45.395+0000] {logging_mixin.py:188} INFO - [2024-07-25T17:55:45.393+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/great_expectations_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_dag.py", line 4, in <module>
    from great_expectations_provider.operators.great_expectations import GreatExpectationsOperator
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-07-25T17:55:45.395+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T17:55:45.406+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 0.024 seconds
[2024-07-25T17:56:16.119+0000] {processor.py:161} INFO - Started process (PID=329) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T17:56:16.120+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T17:56:16.122+0000] {logging_mixin.py:188} INFO - [2024-07-25T17:56:16.122+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T17:56:16.128+0000] {logging_mixin.py:188} INFO - [2024-07-25T17:56:16.127+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/great_expectations_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_dag.py", line 4, in <module>
    from great_expectations_provider.operators.great_expectations import GreatExpectationsOperator
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-07-25T17:56:16.128+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T17:56:16.143+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 0.027 seconds
[2024-07-25T17:56:46.820+0000] {processor.py:161} INFO - Started process (PID=389) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T17:56:46.820+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T17:56:46.821+0000] {logging_mixin.py:188} INFO - [2024-07-25T17:56:46.821+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T17:56:46.824+0000] {logging_mixin.py:188} INFO - [2024-07-25T17:56:46.823+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/great_expectations_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_dag.py", line 4, in <module>
    from great_expectations_provider.operators.great_expectations import GreatExpectationsOperator
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-07-25T17:56:46.825+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T17:56:46.837+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 0.020 seconds
[2024-07-25T17:57:17.452+0000] {processor.py:161} INFO - Started process (PID=449) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T17:57:17.453+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T17:57:17.454+0000] {logging_mixin.py:188} INFO - [2024-07-25T17:57:17.454+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T17:57:17.459+0000] {logging_mixin.py:188} INFO - [2024-07-25T17:57:17.457+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/great_expectations_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_dag.py", line 4, in <module>
    from great_expectations_provider.operators.great_expectations import GreatExpectationsOperator
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-07-25T17:57:17.459+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T17:57:17.470+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 0.021 seconds
[2024-07-25T17:57:48.048+0000] {processor.py:161} INFO - Started process (PID=509) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T17:57:48.049+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T17:57:48.050+0000] {logging_mixin.py:188} INFO - [2024-07-25T17:57:48.050+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T17:57:48.053+0000] {logging_mixin.py:188} INFO - [2024-07-25T17:57:48.052+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/great_expectations_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_dag.py", line 4, in <module>
    from great_expectations_provider.operators.great_expectations import GreatExpectationsOperator
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-07-25T17:57:48.054+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T17:57:48.063+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 0.018 seconds
[2024-07-25T17:58:18.736+0000] {processor.py:161} INFO - Started process (PID=569) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T17:58:18.737+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T17:58:18.738+0000] {logging_mixin.py:188} INFO - [2024-07-25T17:58:18.737+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T17:58:18.741+0000] {logging_mixin.py:188} INFO - [2024-07-25T17:58:18.740+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/great_expectations_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_dag.py", line 4, in <module>
    from great_expectations_provider.operators.great_expectations import GreatExpectationsOperator
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-07-25T17:58:18.741+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T17:58:18.752+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 0.019 seconds
[2024-07-25T17:58:49.427+0000] {processor.py:161} INFO - Started process (PID=629) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T17:58:49.428+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T17:58:49.429+0000] {logging_mixin.py:188} INFO - [2024-07-25T17:58:49.429+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T17:58:49.432+0000] {logging_mixin.py:188} INFO - [2024-07-25T17:58:49.432+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/great_expectations_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_dag.py", line 4, in <module>
    from great_expectations_provider.operators.great_expectations import GreatExpectationsOperator
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-07-25T17:58:49.433+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T17:58:49.448+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 0.025 seconds
[2024-07-25T17:59:20.129+0000] {processor.py:161} INFO - Started process (PID=689) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T17:59:20.130+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T17:59:20.132+0000] {logging_mixin.py:188} INFO - [2024-07-25T17:59:20.132+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T17:59:20.137+0000] {logging_mixin.py:188} INFO - [2024-07-25T17:59:20.135+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/great_expectations_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_dag.py", line 4, in <module>
    from great_expectations_provider.operators.great_expectations import GreatExpectationsOperator
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-07-25T17:59:20.137+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T17:59:20.151+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 0.025 seconds
[2024-07-25T17:59:50.869+0000] {processor.py:161} INFO - Started process (PID=749) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T17:59:50.870+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T17:59:50.871+0000] {logging_mixin.py:188} INFO - [2024-07-25T17:59:50.871+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T17:59:50.876+0000] {logging_mixin.py:188} INFO - [2024-07-25T17:59:50.875+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/great_expectations_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_dag.py", line 4, in <module>
    from great_expectations_provider.operators.great_expectations import GreatExpectationsOperator
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-07-25T17:59:50.877+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T17:59:50.892+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 0.029 seconds
[2024-07-25T18:00:21.607+0000] {processor.py:161} INFO - Started process (PID=809) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:00:21.608+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T18:00:21.610+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:00:21.609+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:00:21.615+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:00:21.614+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/great_expectations_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_dag.py", line 4, in <module>
    from great_expectations_provider.operators.great_expectations import GreatExpectationsOperator
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-07-25T18:00:21.616+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:00:21.632+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 0.033 seconds
[2024-07-25T18:00:52.352+0000] {processor.py:161} INFO - Started process (PID=869) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:00:52.353+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T18:00:52.355+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:00:52.355+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:00:52.360+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:00:52.358+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/great_expectations_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_dag.py", line 4, in <module>
    from great_expectations_provider.operators.great_expectations import GreatExpectationsOperator
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-07-25T18:00:52.361+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:00:52.377+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 0.029 seconds
[2024-07-25T18:01:23.105+0000] {processor.py:161} INFO - Started process (PID=929) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:01:23.106+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T18:01:23.107+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:01:23.107+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:01:23.110+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:01:23.109+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/great_expectations_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_dag.py", line 4, in <module>
    from great_expectations_provider.operators.great_expectations import GreatExpectationsOperator
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-07-25T18:01:23.110+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:01:23.121+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 0.019 seconds
[2024-07-25T18:01:53.157+0000] {processor.py:161} INFO - Started process (PID=989) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:01:53.158+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T18:01:53.159+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:01:53.159+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:01:53.162+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:01:53.161+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/great_expectations_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_dag.py", line 4, in <module>
    from great_expectations_provider.operators.great_expectations import GreatExpectationsOperator
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-07-25T18:01:53.162+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:01:53.173+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 0.020 seconds
[2024-07-25T18:02:23.222+0000] {processor.py:161} INFO - Started process (PID=1049) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:02:23.223+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T18:02:23.224+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:02:23.224+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:02:23.228+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:02:23.227+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/great_expectations_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_dag.py", line 4, in <module>
    from great_expectations_provider.operators.great_expectations import GreatExpectationsOperator
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-07-25T18:02:23.228+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:02:23.237+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 0.019 seconds
[2024-07-25T18:02:53.373+0000] {processor.py:161} INFO - Started process (PID=1109) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:02:53.375+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T18:02:53.378+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:02:53.378+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:02:53.385+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:02:53.383+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/great_expectations_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_dag.py", line 4, in <module>
    from great_expectations_provider.operators.great_expectations import GreatExpectationsOperator
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-07-25T18:02:53.386+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:02:53.403+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 0.036 seconds
[2024-07-25T18:03:23.830+0000] {processor.py:161} INFO - Started process (PID=1169) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:03:23.831+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T18:03:23.832+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:03:23.832+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:03:23.836+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:03:23.835+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/great_expectations_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_dag.py", line 4, in <module>
    from great_expectations_provider.operators.great_expectations import GreatExpectationsOperator
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-07-25T18:03:23.837+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:03:23.850+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 0.024 seconds
[2024-07-25T18:03:44.671+0000] {processor.py:161} INFO - Started process (PID=1228) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:03:44.672+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T18:03:44.674+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:03:44.674+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:03:45.795+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/sqlalchemy_redshift/commands.py:31 SyntaxWarning: invalid escape sequence '\-'
[2024-07-25T18:03:45.796+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/sqlalchemy_redshift/commands.py:33 SyntaxWarning: invalid escape sequence '\-'
[2024-07-25T18:03:46.837+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:03:46.837+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/snowflake/sqlalchemy/base.py:1068: SAWarning: The GenericFunction 'flatten' is already registered and is going to be overridden.
  functions.register_function("flatten", flatten)
[2024-07-25T18:03:47.708+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:03:47.707+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/great_expectations_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_dag.py", line 5, in <module>
    from great_expectations.datasource import SQLTableBatchKwargsGenerator
ImportError: cannot import name 'SQLTableBatchKwargsGenerator' from 'great_expectations.datasource' (/home/airflow/.local/lib/python3.12/site-packages/great_expectations/datasource/__init__.py)
[2024-07-25T18:03:47.709+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:03:47.718+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 3.053 seconds
[2024-07-25T18:04:07.539+0000] {processor.py:161} INFO - Started process (PID=1297) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:04:07.541+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T18:04:07.544+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:04:07.544+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:04:08.547+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:04:08.547+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/snowflake/sqlalchemy/base.py:1068: SAWarning: The GenericFunction 'flatten' is already registered and is going to be overridden.
  functions.register_function("flatten", flatten)
[2024-07-25T18:04:09.199+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:04:09.198+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/great_expectations_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_dag.py", line 5, in <module>
    from great_expectations.datasource import SQLTableBatchKwargsGenerator
ImportError: cannot import name 'SQLTableBatchKwargsGenerator' from 'great_expectations.datasource' (/home/airflow/.local/lib/python3.12/site-packages/great_expectations/datasource/__init__.py)
[2024-07-25T18:04:09.200+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:04:09.209+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 1.680 seconds
[2024-07-25T18:04:39.329+0000] {processor.py:161} INFO - Started process (PID=1366) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:04:39.331+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T18:04:39.334+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:04:39.333+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:04:40.287+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:04:40.287+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/snowflake/sqlalchemy/base.py:1068: SAWarning: The GenericFunction 'flatten' is already registered and is going to be overridden.
  functions.register_function("flatten", flatten)
[2024-07-25T18:04:40.866+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:04:40.865+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/great_expectations_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_dag.py", line 5, in <module>
    from great_expectations.datasource import SQLTableBatchKwargsGenerator
ImportError: cannot import name 'SQLTableBatchKwargsGenerator' from 'great_expectations.datasource' (/home/airflow/.local/lib/python3.12/site-packages/great_expectations/datasource/__init__.py)
[2024-07-25T18:04:40.867+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:04:40.875+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 1.553 seconds
[2024-07-25T18:05:11.008+0000] {processor.py:161} INFO - Started process (PID=1435) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:05:11.009+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T18:05:11.011+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:05:11.011+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:05:11.874+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:05:11.874+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/snowflake/sqlalchemy/base.py:1068: SAWarning: The GenericFunction 'flatten' is already registered and is going to be overridden.
  functions.register_function("flatten", flatten)
[2024-07-25T18:05:12.434+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:05:12.433+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/great_expectations_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_dag.py", line 5, in <module>
    from great_expectations.datasource import SQLTableBatchKwargsGenerator
ImportError: cannot import name 'SQLTableBatchKwargsGenerator' from 'great_expectations.datasource' (/home/airflow/.local/lib/python3.12/site-packages/great_expectations/datasource/__init__.py)
[2024-07-25T18:05:12.435+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:05:12.442+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 1.441 seconds
[2024-07-25T18:05:42.927+0000] {processor.py:161} INFO - Started process (PID=1504) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:05:42.928+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T18:05:42.931+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:05:42.930+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:05:43.850+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:05:43.850+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/snowflake/sqlalchemy/base.py:1068: SAWarning: The GenericFunction 'flatten' is already registered and is going to be overridden.
  functions.register_function("flatten", flatten)
[2024-07-25T18:05:44.498+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:05:44.497+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/great_expectations_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_dag.py", line 5, in <module>
    from great_expectations.datasource import SQLTableBatchKwargsGenerator
ImportError: cannot import name 'SQLTableBatchKwargsGenerator' from 'great_expectations.datasource' (/home/airflow/.local/lib/python3.12/site-packages/great_expectations/datasource/__init__.py)
[2024-07-25T18:05:44.498+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:05:44.505+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 1.586 seconds
[2024-07-25T18:06:14.606+0000] {processor.py:161} INFO - Started process (PID=1573) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:06:14.607+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T18:06:14.608+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:06:14.608+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:06:15.610+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:06:15.609+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/snowflake/sqlalchemy/base.py:1068: SAWarning: The GenericFunction 'flatten' is already registered and is going to be overridden.
  functions.register_function("flatten", flatten)
[2024-07-25T18:06:16.240+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:06:16.239+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/great_expectations_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_dag.py", line 5, in <module>
    from great_expectations.datasource import SQLTableBatchKwargsGenerator
ImportError: cannot import name 'SQLTableBatchKwargsGenerator' from 'great_expectations.datasource' (/home/airflow/.local/lib/python3.12/site-packages/great_expectations/datasource/__init__.py)
[2024-07-25T18:06:16.240+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:06:16.250+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 1.648 seconds
[2024-07-25T18:06:47.140+0000] {processor.py:161} INFO - Started process (PID=1642) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:06:47.142+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T18:06:47.145+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:06:47.144+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:06:48.049+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:06:48.049+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/snowflake/sqlalchemy/base.py:1068: SAWarning: The GenericFunction 'flatten' is already registered and is going to be overridden.
  functions.register_function("flatten", flatten)
[2024-07-25T18:06:48.617+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:06:48.615+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/great_expectations_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_dag.py", line 5, in <module>
    from great_expectations.datasource import SQLTableBatchKwargsGenerator
ImportError: cannot import name 'SQLTableBatchKwargsGenerator' from 'great_expectations.datasource' (/home/airflow/.local/lib/python3.12/site-packages/great_expectations/datasource/__init__.py)
[2024-07-25T18:06:48.617+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:06:48.626+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 1.498 seconds
[2024-07-25T18:07:19.356+0000] {processor.py:161} INFO - Started process (PID=1711) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:07:19.359+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T18:07:19.363+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:07:19.362+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:07:20.360+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:07:20.360+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/snowflake/sqlalchemy/base.py:1068: SAWarning: The GenericFunction 'flatten' is already registered and is going to be overridden.
  functions.register_function("flatten", flatten)
[2024-07-25T18:07:21.006+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:07:21.005+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/great_expectations_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_dag.py", line 5, in <module>
    from great_expectations.datasource import SQLTableBatchKwargsGenerator
ImportError: cannot import name 'SQLTableBatchKwargsGenerator' from 'great_expectations.datasource' (/home/airflow/.local/lib/python3.12/site-packages/great_expectations/datasource/__init__.py)
[2024-07-25T18:07:21.006+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:07:21.015+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 1.670 seconds
[2024-07-25T18:07:51.204+0000] {processor.py:161} INFO - Started process (PID=1780) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:07:51.206+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T18:07:51.212+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:07:51.211+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:07:52.420+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:07:52.420+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/snowflake/sqlalchemy/base.py:1068: SAWarning: The GenericFunction 'flatten' is already registered and is going to be overridden.
  functions.register_function("flatten", flatten)
[2024-07-25T18:07:53.087+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:07:53.086+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/great_expectations_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_dag.py", line 5, in <module>
    from great_expectations.datasource import SQLTableBatchKwargsGenerator
ImportError: cannot import name 'SQLTableBatchKwargsGenerator' from 'great_expectations.datasource' (/home/airflow/.local/lib/python3.12/site-packages/great_expectations/datasource/__init__.py)
[2024-07-25T18:07:53.088+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:07:53.099+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 1.910 seconds
[2024-07-25T18:08:23.795+0000] {processor.py:161} INFO - Started process (PID=1849) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:08:23.797+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T18:08:23.802+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:08:23.801+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:08:24.886+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:08:24.886+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/snowflake/sqlalchemy/base.py:1068: SAWarning: The GenericFunction 'flatten' is already registered and is going to be overridden.
  functions.register_function("flatten", flatten)
[2024-07-25T18:08:25.500+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:08:25.499+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/great_expectations_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_dag.py", line 5, in <module>
    from great_expectations.datasource import SQLTableBatchKwargsGenerator
ImportError: cannot import name 'SQLTableBatchKwargsGenerator' from 'great_expectations.datasource' (/home/airflow/.local/lib/python3.12/site-packages/great_expectations/datasource/__init__.py)
[2024-07-25T18:08:25.501+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:08:25.510+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 1.734 seconds
[2024-07-25T18:08:56.441+0000] {processor.py:161} INFO - Started process (PID=1918) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:08:56.442+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T18:08:56.446+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:08:56.446+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:08:57.603+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:08:57.602+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/snowflake/sqlalchemy/base.py:1068: SAWarning: The GenericFunction 'flatten' is already registered and is going to be overridden.
  functions.register_function("flatten", flatten)
[2024-07-25T18:08:58.427+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:08:58.425+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/great_expectations_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_dag.py", line 5, in <module>
    from great_expectations.datasource import SQLTableBatchKwargsGenerator
ImportError: cannot import name 'SQLTableBatchKwargsGenerator' from 'great_expectations.datasource' (/home/airflow/.local/lib/python3.12/site-packages/great_expectations/datasource/__init__.py)
[2024-07-25T18:08:58.428+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:08:58.443+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 2.012 seconds
[2024-07-25T18:09:29.165+0000] {processor.py:161} INFO - Started process (PID=1993) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:09:29.166+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T18:09:29.170+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:09:29.170+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:09:30.297+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:09:30.297+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/snowflake/sqlalchemy/base.py:1068: SAWarning: The GenericFunction 'flatten' is already registered and is going to be overridden.
  functions.register_function("flatten", flatten)
[2024-07-25T18:09:30.929+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:09:30.928+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/great_expectations_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_dag.py", line 5, in <module>
    from great_expectations.datasource import SQLTableBatchKwargsGenerator
ImportError: cannot import name 'SQLTableBatchKwargsGenerator' from 'great_expectations.datasource' (/home/airflow/.local/lib/python3.12/site-packages/great_expectations/datasource/__init__.py)
[2024-07-25T18:09:30.929+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:09:30.937+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 1.780 seconds
[2024-07-25T18:10:01.793+0000] {processor.py:161} INFO - Started process (PID=2065) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:10:01.793+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T18:10:01.795+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:10:01.795+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:10:02.846+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:10:02.846+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/snowflake/sqlalchemy/base.py:1068: SAWarning: The GenericFunction 'flatten' is already registered and is going to be overridden.
  functions.register_function("flatten", flatten)
[2024-07-25T18:10:03.501+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:10:03.500+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/great_expectations_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_dag.py", line 5, in <module>
    from great_expectations.datasource import SQLTableBatchKwargsGenerator
ImportError: cannot import name 'SQLTableBatchKwargsGenerator' from 'great_expectations.datasource' (/home/airflow/.local/lib/python3.12/site-packages/great_expectations/datasource/__init__.py)
[2024-07-25T18:10:03.502+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:10:03.510+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 1.723 seconds
[2024-07-25T18:10:34.433+0000] {processor.py:161} INFO - Started process (PID=2139) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:10:34.434+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T18:10:34.436+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:10:34.436+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:10:35.501+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:10:35.501+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/snowflake/sqlalchemy/base.py:1068: SAWarning: The GenericFunction 'flatten' is already registered and is going to be overridden.
  functions.register_function("flatten", flatten)
[2024-07-25T18:10:36.207+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:10:36.206+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/great_expectations_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_dag.py", line 5, in <module>
    from great_expectations.datasource import SQLTableBatchKwargsGenerator
ImportError: cannot import name 'SQLTableBatchKwargsGenerator' from 'great_expectations.datasource' (/home/airflow/.local/lib/python3.12/site-packages/great_expectations/datasource/__init__.py)
[2024-07-25T18:10:36.208+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:10:36.219+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 1.794 seconds
[2024-07-25T18:11:06.315+0000] {processor.py:161} INFO - Started process (PID=2223) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:11:06.318+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T18:11:06.320+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:11:06.319+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:11:07.414+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:11:07.413+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/snowflake/sqlalchemy/base.py:1068: SAWarning: The GenericFunction 'flatten' is already registered and is going to be overridden.
  functions.register_function("flatten", flatten)
[2024-07-25T18:11:08.026+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:11:08.025+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/great_expectations_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_dag.py", line 5, in <module>
    from great_expectations.datasource import SQLTableBatchKwargsGenerator
ImportError: cannot import name 'SQLTableBatchKwargsGenerator' from 'great_expectations.datasource' (/home/airflow/.local/lib/python3.12/site-packages/great_expectations/datasource/__init__.py)
[2024-07-25T18:11:08.027+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:11:08.035+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 1.723 seconds
[2024-07-25T18:11:38.532+0000] {processor.py:161} INFO - Started process (PID=2312) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:11:38.533+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T18:11:38.535+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:11:38.534+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:11:39.588+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:11:39.588+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/snowflake/sqlalchemy/base.py:1068: SAWarning: The GenericFunction 'flatten' is already registered and is going to be overridden.
  functions.register_function("flatten", flatten)
[2024-07-25T18:11:40.287+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:11:40.285+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/great_expectations_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_dag.py", line 5, in <module>
    from great_expectations.datasource import SQLTableBatchKwargsGenerator
ImportError: cannot import name 'SQLTableBatchKwargsGenerator' from 'great_expectations.datasource' (/home/airflow/.local/lib/python3.12/site-packages/great_expectations/datasource/__init__.py)
[2024-07-25T18:11:40.287+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:11:40.294+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 1.767 seconds
[2024-07-25T18:12:10.967+0000] {processor.py:161} INFO - Started process (PID=2387) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:12:10.968+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T18:12:10.971+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:12:10.970+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:12:11.949+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:12:11.949+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/snowflake/sqlalchemy/base.py:1068: SAWarning: The GenericFunction 'flatten' is already registered and is going to be overridden.
  functions.register_function("flatten", flatten)
[2024-07-25T18:12:12.756+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:12:12.754+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/great_expectations_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_dag.py", line 5, in <module>
    from great_expectations.datasource import SQLTableBatchKwargsGenerator
ImportError: cannot import name 'SQLTableBatchKwargsGenerator' from 'great_expectations.datasource' (/home/airflow/.local/lib/python3.12/site-packages/great_expectations/datasource/__init__.py)
[2024-07-25T18:12:12.757+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:12:12.767+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 1.808 seconds
[2024-07-25T18:12:43.002+0000] {processor.py:161} INFO - Started process (PID=2459) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:12:43.003+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T18:12:43.004+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:12:43.003+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:12:44.239+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:12:44.239+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/snowflake/sqlalchemy/base.py:1068: SAWarning: The GenericFunction 'flatten' is already registered and is going to be overridden.
  functions.register_function("flatten", flatten)
[2024-07-25T18:12:45.007+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:12:45.005+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/great_expectations_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_dag.py", line 5, in <module>
    from great_expectations.datasource import SQLTableBatchKwargsGenerator
ImportError: cannot import name 'SQLTableBatchKwargsGenerator' from 'great_expectations.datasource' (/home/airflow/.local/lib/python3.12/site-packages/great_expectations/datasource/__init__.py)
[2024-07-25T18:12:45.007+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:12:45.016+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 2.017 seconds
[2024-07-25T18:13:15.785+0000] {processor.py:161} INFO - Started process (PID=2528) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:13:15.787+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T18:13:15.791+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:13:15.790+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:13:16.722+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:13:16.722+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/snowflake/sqlalchemy/base.py:1068: SAWarning: The GenericFunction 'flatten' is already registered and is going to be overridden.
  functions.register_function("flatten", flatten)
[2024-07-25T18:13:17.478+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:13:17.477+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/great_expectations_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_dag.py", line 5, in <module>
    from great_expectations.datasource import SQLTableBatchKwargsGenerator
ImportError: cannot import name 'SQLTableBatchKwargsGenerator' from 'great_expectations.datasource' (/home/airflow/.local/lib/python3.12/site-packages/great_expectations/datasource/__init__.py)
[2024-07-25T18:13:17.478+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:13:17.492+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 1.717 seconds
[2024-07-25T18:13:48.277+0000] {processor.py:161} INFO - Started process (PID=2596) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:13:48.278+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T18:13:48.279+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:13:48.279+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:13:49.237+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:13:49.237+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/snowflake/sqlalchemy/base.py:1068: SAWarning: The GenericFunction 'flatten' is already registered and is going to be overridden.
  functions.register_function("flatten", flatten)
[2024-07-25T18:13:49.860+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:13:49.859+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/great_expectations_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_dag.py", line 5, in <module>
    from great_expectations.datasource import SQLTableBatchKwargsGenerator
ImportError: cannot import name 'SQLTableBatchKwargsGenerator' from 'great_expectations.datasource' (/home/airflow/.local/lib/python3.12/site-packages/great_expectations/datasource/__init__.py)
[2024-07-25T18:13:49.861+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:13:49.870+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 1.600 seconds
[2024-07-25T18:14:20.586+0000] {processor.py:161} INFO - Started process (PID=2665) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:14:20.587+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T18:14:20.591+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:14:20.590+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:14:21.498+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:14:21.498+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/snowflake/sqlalchemy/base.py:1068: SAWarning: The GenericFunction 'flatten' is already registered and is going to be overridden.
  functions.register_function("flatten", flatten)
[2024-07-25T18:14:22.123+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:14:22.122+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/great_expectations_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_dag.py", line 5, in <module>
    from great_expectations.datasource import SQLTableBatchKwargsGenerator
ImportError: cannot import name 'SQLTableBatchKwargsGenerator' from 'great_expectations.datasource' (/home/airflow/.local/lib/python3.12/site-packages/great_expectations/datasource/__init__.py)
[2024-07-25T18:14:22.124+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:14:22.132+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 1.554 seconds
[2024-07-25T18:14:52.881+0000] {processor.py:161} INFO - Started process (PID=2734) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:14:52.882+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T18:14:52.885+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:14:52.885+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:14:53.842+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:14:53.842+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/snowflake/sqlalchemy/base.py:1068: SAWarning: The GenericFunction 'flatten' is already registered and is going to be overridden.
  functions.register_function("flatten", flatten)
[2024-07-25T18:14:54.456+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:14:54.455+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/great_expectations_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_dag.py", line 5, in <module>
    from great_expectations.datasource import SQLTableBatchKwargsGenerator
ImportError: cannot import name 'SQLTableBatchKwargsGenerator' from 'great_expectations.datasource' (/home/airflow/.local/lib/python3.12/site-packages/great_expectations/datasource/__init__.py)
[2024-07-25T18:14:54.457+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:14:54.467+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 1.596 seconds
[2024-07-25T18:15:25.129+0000] {processor.py:161} INFO - Started process (PID=2803) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:15:25.130+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T18:15:25.133+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:15:25.132+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:15:26.059+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:15:26.059+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/snowflake/sqlalchemy/base.py:1068: SAWarning: The GenericFunction 'flatten' is already registered and is going to be overridden.
  functions.register_function("flatten", flatten)
[2024-07-25T18:15:26.682+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:15:26.681+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/great_expectations_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_dag.py", line 5, in <module>
    from great_expectations.datasource import SQLTableBatchKwargsGenerator
ImportError: cannot import name 'SQLTableBatchKwargsGenerator' from 'great_expectations.datasource' (/home/airflow/.local/lib/python3.12/site-packages/great_expectations/datasource/__init__.py)
[2024-07-25T18:15:26.683+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:15:26.691+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 1.569 seconds
[2024-07-25T18:15:57.490+0000] {processor.py:161} INFO - Started process (PID=2872) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:15:57.491+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T18:15:57.492+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:15:57.492+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:15:58.457+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:15:58.457+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/snowflake/sqlalchemy/base.py:1068: SAWarning: The GenericFunction 'flatten' is already registered and is going to be overridden.
  functions.register_function("flatten", flatten)
[2024-07-25T18:15:59.139+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:15:59.138+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/great_expectations_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_dag.py", line 5, in <module>
    from great_expectations.datasource import SQLTableBatchKwargsGenerator
ImportError: cannot import name 'SQLTableBatchKwargsGenerator' from 'great_expectations.datasource' (/home/airflow/.local/lib/python3.12/site-packages/great_expectations/datasource/__init__.py)
[2024-07-25T18:15:59.140+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:15:59.148+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 1.663 seconds
[2024-07-25T18:16:29.825+0000] {processor.py:161} INFO - Started process (PID=2947) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:16:29.827+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T18:16:29.830+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:16:29.830+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:16:30.814+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:16:30.814+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/snowflake/sqlalchemy/base.py:1068: SAWarning: The GenericFunction 'flatten' is already registered and is going to be overridden.
  functions.register_function("flatten", flatten)
[2024-07-25T18:16:31.469+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:16:31.468+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/great_expectations_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_dag.py", line 5, in <module>
    from great_expectations.datasource import SQLTableBatchKwargsGenerator
ImportError: cannot import name 'SQLTableBatchKwargsGenerator' from 'great_expectations.datasource' (/home/airflow/.local/lib/python3.12/site-packages/great_expectations/datasource/__init__.py)
[2024-07-25T18:16:31.470+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:16:31.481+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 1.664 seconds
[2024-07-25T18:17:02.205+0000] {processor.py:161} INFO - Started process (PID=3016) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:17:02.206+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T18:17:02.209+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:17:02.209+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:17:03.265+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:17:03.264+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/snowflake/sqlalchemy/base.py:1068: SAWarning: The GenericFunction 'flatten' is already registered and is going to be overridden.
  functions.register_function("flatten", flatten)
[2024-07-25T18:17:03.913+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:17:03.912+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/great_expectations_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_dag.py", line 5, in <module>
    from great_expectations.datasource import SQLTableBatchKwargsGenerator
ImportError: cannot import name 'SQLTableBatchKwargsGenerator' from 'great_expectations.datasource' (/home/airflow/.local/lib/python3.12/site-packages/great_expectations/datasource/__init__.py)
[2024-07-25T18:17:03.914+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:17:03.923+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 1.726 seconds
[2024-07-25T18:17:34.608+0000] {processor.py:161} INFO - Started process (PID=3085) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:17:34.609+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T18:17:34.610+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:17:34.610+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:17:35.469+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:17:35.469+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/snowflake/sqlalchemy/base.py:1068: SAWarning: The GenericFunction 'flatten' is already registered and is going to be overridden.
  functions.register_function("flatten", flatten)
[2024-07-25T18:17:36.056+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:17:36.055+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/great_expectations_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_dag.py", line 5, in <module>
    from great_expectations.datasource import SQLTableBatchKwargsGenerator
ImportError: cannot import name 'SQLTableBatchKwargsGenerator' from 'great_expectations.datasource' (/home/airflow/.local/lib/python3.12/site-packages/great_expectations/datasource/__init__.py)
[2024-07-25T18:17:36.056+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:17:36.064+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 1.459 seconds
[2024-07-25T18:18:06.880+0000] {processor.py:161} INFO - Started process (PID=3154) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:18:06.881+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T18:18:06.885+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:18:06.884+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:18:07.821+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:18:07.821+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/snowflake/sqlalchemy/base.py:1068: SAWarning: The GenericFunction 'flatten' is already registered and is going to be overridden.
  functions.register_function("flatten", flatten)
[2024-07-25T18:18:08.462+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:18:08.461+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/great_expectations_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_dag.py", line 5, in <module>
    from great_expectations.datasource import SQLTableBatchKwargsGenerator
ImportError: cannot import name 'SQLTableBatchKwargsGenerator' from 'great_expectations.datasource' (/home/airflow/.local/lib/python3.12/site-packages/great_expectations/datasource/__init__.py)
[2024-07-25T18:18:08.463+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:18:08.470+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 1.596 seconds
[2024-07-25T18:18:39.264+0000] {processor.py:161} INFO - Started process (PID=3231) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:18:39.264+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T18:18:39.265+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:18:39.265+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:18:40.344+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:18:40.344+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/snowflake/sqlalchemy/base.py:1068: SAWarning: The GenericFunction 'flatten' is already registered and is going to be overridden.
  functions.register_function("flatten", flatten)
[2024-07-25T18:18:41.030+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:18:41.029+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/great_expectations_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_dag.py", line 5, in <module>
    from great_expectations.datasource import SQLTableBatchKwargsGenerator
ImportError: cannot import name 'SQLTableBatchKwargsGenerator' from 'great_expectations.datasource' (/home/airflow/.local/lib/python3.12/site-packages/great_expectations/datasource/__init__.py)
[2024-07-25T18:18:41.031+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:18:41.042+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 1.782 seconds
[2024-07-25T18:19:11.815+0000] {processor.py:161} INFO - Started process (PID=3302) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:19:11.816+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T18:19:11.819+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:19:11.818+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:19:13.036+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:19:13.036+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/snowflake/sqlalchemy/base.py:1068: SAWarning: The GenericFunction 'flatten' is already registered and is going to be overridden.
  functions.register_function("flatten", flatten)
[2024-07-25T18:19:13.797+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:19:13.796+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/great_expectations_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_dag.py", line 5, in <module>
    from great_expectations.datasource import SQLTableBatchKwargsGenerator
ImportError: cannot import name 'SQLTableBatchKwargsGenerator' from 'great_expectations.datasource' (/home/airflow/.local/lib/python3.12/site-packages/great_expectations/datasource/__init__.py)
[2024-07-25T18:19:13.798+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:19:13.806+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 1.998 seconds
[2024-07-25T18:19:44.329+0000] {processor.py:161} INFO - Started process (PID=3391) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:19:44.329+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T18:19:44.330+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:19:44.330+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:19:45.349+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:19:45.348+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/snowflake/sqlalchemy/base.py:1068: SAWarning: The GenericFunction 'flatten' is already registered and is going to be overridden.
  functions.register_function("flatten", flatten)
[2024-07-25T18:19:45.973+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:19:45.972+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/great_expectations_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_dag.py", line 5, in <module>
    from great_expectations.datasource import SQLTableBatchKwargsGenerator
ImportError: cannot import name 'SQLTableBatchKwargsGenerator' from 'great_expectations.datasource' (/home/airflow/.local/lib/python3.12/site-packages/great_expectations/datasource/__init__.py)
[2024-07-25T18:19:45.974+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:19:45.981+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 1.655 seconds
[2024-07-25T18:20:16.015+0000] {processor.py:161} INFO - Started process (PID=3475) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:20:16.016+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T18:20:16.017+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:20:16.017+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:20:17.082+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:20:17.082+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/snowflake/sqlalchemy/base.py:1068: SAWarning: The GenericFunction 'flatten' is already registered and is going to be overridden.
  functions.register_function("flatten", flatten)
[2024-07-25T18:20:17.721+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:20:17.720+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/great_expectations_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_dag.py", line 5, in <module>
    from great_expectations.datasource import SQLTableBatchKwargsGenerator
ImportError: cannot import name 'SQLTableBatchKwargsGenerator' from 'great_expectations.datasource' (/home/airflow/.local/lib/python3.12/site-packages/great_expectations/datasource/__init__.py)
[2024-07-25T18:20:17.722+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:20:17.729+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 1.718 seconds
[2024-07-25T18:20:26.883+0000] {processor.py:161} INFO - Started process (PID=3493) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:20:26.885+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T18:20:26.888+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:20:26.888+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:20:27.890+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:20:27.890+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/snowflake/sqlalchemy/base.py:1068: SAWarning: The GenericFunction 'flatten' is already registered and is going to be overridden.
  functions.register_function("flatten", flatten)
[2024-07-25T18:20:28.506+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:20:28.505+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/great_expectations_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_dag.py", line 5, in <module>
    from great_expectations.datasource import SQLTableBatchKwargsGenerator
ImportError: cannot import name 'SQLTableBatchKwargsGenerator' from 'great_expectations.datasource' (/home/airflow/.local/lib/python3.12/site-packages/great_expectations/datasource/__init__.py)
[2024-07-25T18:20:28.506+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:20:28.514+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 1.640 seconds
[2024-07-25T18:20:58.808+0000] {processor.py:161} INFO - Started process (PID=3562) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:20:58.809+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T18:20:58.811+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:20:58.811+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:20:59.885+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:20:59.885+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/snowflake/sqlalchemy/base.py:1068: SAWarning: The GenericFunction 'flatten' is already registered and is going to be overridden.
  functions.register_function("flatten", flatten)
[2024-07-25T18:21:00.525+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:21:00.524+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/great_expectations_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_dag.py", line 5, in <module>
    from great_expectations.datasource import SQLTableBatchKwargsGenerator
ImportError: cannot import name 'SQLTableBatchKwargsGenerator' from 'great_expectations.datasource' (/home/airflow/.local/lib/python3.12/site-packages/great_expectations/datasource/__init__.py)
[2024-07-25T18:21:00.526+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:21:00.535+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 1.733 seconds
[2024-07-25T18:21:31.333+0000] {processor.py:161} INFO - Started process (PID=3637) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:21:31.336+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T18:21:31.339+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:21:31.339+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:21:32.257+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:21:32.257+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/snowflake/sqlalchemy/base.py:1068: SAWarning: The GenericFunction 'flatten' is already registered and is going to be overridden.
  functions.register_function("flatten", flatten)
[2024-07-25T18:21:32.855+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:21:32.854+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/great_expectations_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_dag.py", line 5, in <module>
    from great_expectations.datasource import SQLTableBatchKwargsGenerator
ImportError: cannot import name 'SQLTableBatchKwargsGenerator' from 'great_expectations.datasource' (/home/airflow/.local/lib/python3.12/site-packages/great_expectations/datasource/__init__.py)
[2024-07-25T18:21:32.855+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:21:32.865+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 1.543 seconds
[2024-07-25T18:22:03.515+0000] {processor.py:161} INFO - Started process (PID=3706) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:22:03.516+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T18:22:03.517+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:22:03.517+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:22:04.535+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:22:04.534+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/snowflake/sqlalchemy/base.py:1068: SAWarning: The GenericFunction 'flatten' is already registered and is going to be overridden.
  functions.register_function("flatten", flatten)
[2024-07-25T18:22:05.146+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:22:05.145+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/great_expectations_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_dag.py", line 5, in <module>
    from great_expectations.datasource import SQLTableBatchKwargsGenerator
ImportError: cannot import name 'SQLTableBatchKwargsGenerator' from 'great_expectations.datasource' (/home/airflow/.local/lib/python3.12/site-packages/great_expectations/datasource/__init__.py)
[2024-07-25T18:22:05.147+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:22:05.156+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 1.644 seconds
[2024-07-25T18:22:35.862+0000] {processor.py:161} INFO - Started process (PID=3775) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:22:35.865+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T18:22:35.869+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:22:35.868+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:22:36.754+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:22:36.754+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/snowflake/sqlalchemy/base.py:1068: SAWarning: The GenericFunction 'flatten' is already registered and is going to be overridden.
  functions.register_function("flatten", flatten)
[2024-07-25T18:22:37.316+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:22:37.315+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/great_expectations_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_dag.py", line 5, in <module>
    from great_expectations.datasource import SQLTableBatchKwargsGenerator
ImportError: cannot import name 'SQLTableBatchKwargsGenerator' from 'great_expectations.datasource' (/home/airflow/.local/lib/python3.12/site-packages/great_expectations/datasource/__init__.py)
[2024-07-25T18:22:37.317+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:22:37.325+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 1.471 seconds
[2024-07-25T18:23:03.081+0000] {processor.py:161} INFO - Started process (PID=3844) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:23:03.082+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T18:23:03.083+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:23:03.083+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:23:03.093+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:23:03.092+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/great_expectations_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_dag.py", line 4, in <module>
    from expectations.data_context import DataContext
ModuleNotFoundError: No module named 'expectations.data_context'
[2024-07-25T18:23:03.094+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:23:03.110+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 0.034 seconds
[2024-07-25T18:23:33.715+0000] {processor.py:161} INFO - Started process (PID=3904) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:23:33.716+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T18:23:33.717+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:23:33.717+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:23:33.723+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:23:33.722+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/great_expectations_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_dag.py", line 4, in <module>
    from expectations.data_context import DataContext
ModuleNotFoundError: No module named 'expectations.data_context'
[2024-07-25T18:23:33.724+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:23:33.735+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 0.023 seconds
[2024-07-25T18:24:04.559+0000] {processor.py:161} INFO - Started process (PID=3964) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:24:04.561+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T18:24:04.563+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:24:04.563+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:24:04.570+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:24:04.569+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/great_expectations_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_dag.py", line 4, in <module>
    from expectations.data_context import DataContext
ModuleNotFoundError: No module named 'expectations.data_context'
[2024-07-25T18:24:04.571+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:24:04.610+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 0.056 seconds
[2024-07-25T18:24:35.342+0000] {processor.py:161} INFO - Started process (PID=4024) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:24:35.343+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T18:24:35.344+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:24:35.344+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:24:35.349+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:24:35.348+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/great_expectations_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_dag.py", line 4, in <module>
    from expectations.data_context import DataContext
ModuleNotFoundError: No module named 'expectations.data_context'
[2024-07-25T18:24:35.349+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:24:35.363+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 0.026 seconds
[2024-07-25T18:25:06.215+0000] {processor.py:161} INFO - Started process (PID=4084) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:25:06.216+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T18:25:06.218+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:25:06.217+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:25:06.224+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:25:06.223+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/great_expectations_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_dag.py", line 4, in <module>
    from expectations.data_context import DataContext
ModuleNotFoundError: No module named 'expectations.data_context'
[2024-07-25T18:25:06.225+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:25:06.242+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 0.032 seconds
[2024-07-25T18:25:23.710+0000] {processor.py:161} INFO - Started process (PID=4135) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:25:23.711+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T18:25:23.713+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:25:23.713+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:25:24.709+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:25:24.709+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/snowflake/sqlalchemy/base.py:1068: SAWarning: The GenericFunction 'flatten' is already registered and is going to be overridden.
  functions.register_function("flatten", flatten)
[2024-07-25T18:25:25.369+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:25:25.367+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/great_expectations_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_dag.py", line 72, in <module>
    default_args=default_args,
                 ^^^^^^^^^^^^
NameError: name 'default_args' is not defined
[2024-07-25T18:25:25.371+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:25:25.378+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 1.672 seconds
[2024-07-25T18:25:53.039+0000] {processor.py:161} INFO - Started process (PID=4199) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:25:53.040+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T18:25:53.041+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:25:53.041+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:25:54.119+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:25:54.119+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/snowflake/sqlalchemy/base.py:1068: SAWarning: The GenericFunction 'flatten' is already registered and is going to be overridden.
  functions.register_function("flatten", flatten)
[2024-07-25T18:25:54.753+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:25:54.759+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 1.724 seconds
[2024-07-25T18:26:24.905+0000] {processor.py:161} INFO - Started process (PID=4273) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:26:24.906+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T18:26:24.908+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:26:24.907+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:26:25.900+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:26:25.900+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/snowflake/sqlalchemy/base.py:1068: SAWarning: The GenericFunction 'flatten' is already registered and is going to be overridden.
  functions.register_function("flatten", flatten)
[2024-07-25T18:26:26.622+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:26:26.631+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 1.731 seconds
[2024-07-25T18:26:56.893+0000] {processor.py:161} INFO - Started process (PID=4343) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:26:56.894+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T18:26:56.896+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:26:56.896+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:26:57.917+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:26:57.917+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/snowflake/sqlalchemy/base.py:1068: SAWarning: The GenericFunction 'flatten' is already registered and is going to be overridden.
  functions.register_function("flatten", flatten)
[2024-07-25T18:26:58.543+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:26:58.549+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 1.665 seconds
[2024-07-25T18:27:29.015+0000] {processor.py:161} INFO - Started process (PID=4413) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:27:29.016+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T18:27:29.018+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:27:29.018+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:27:30.098+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:27:30.097+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/snowflake/sqlalchemy/base.py:1068: SAWarning: The GenericFunction 'flatten' is already registered and is going to be overridden.
  functions.register_function("flatten", flatten)
[2024-07-25T18:27:30.796+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:27:30.805+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 1.797 seconds
[2024-07-25T18:28:01.643+0000] {processor.py:161} INFO - Started process (PID=4488) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:28:01.644+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T18:28:01.645+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:28:01.645+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:28:02.591+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:28:02.591+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/snowflake/sqlalchemy/base.py:1068: SAWarning: The GenericFunction 'flatten' is already registered and is going to be overridden.
  functions.register_function("flatten", flatten)
[2024-07-25T18:28:03.168+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:28:03.175+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 1.536 seconds
[2024-07-25T18:28:34.010+0000] {processor.py:161} INFO - Started process (PID=4557) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:28:34.011+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T18:28:34.013+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:28:34.013+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:28:35.025+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:28:35.025+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/snowflake/sqlalchemy/base.py:1068: SAWarning: The GenericFunction 'flatten' is already registered and is going to be overridden.
  functions.register_function("flatten", flatten)
[2024-07-25T18:28:35.689+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:28:35.699+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 1.696 seconds
[2024-07-25T18:29:06.452+0000] {processor.py:161} INFO - Started process (PID=4626) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:29:06.453+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T18:29:06.455+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:29:06.454+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:29:07.438+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:29:07.438+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/snowflake/sqlalchemy/base.py:1068: SAWarning: The GenericFunction 'flatten' is already registered and is going to be overridden.
  functions.register_function("flatten", flatten)
[2024-07-25T18:29:08.030+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:29:08.036+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 1.588 seconds
[2024-07-25T18:29:38.693+0000] {processor.py:161} INFO - Started process (PID=4695) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:29:38.693+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T18:29:38.695+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:29:38.694+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:29:39.809+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:29:39.809+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/snowflake/sqlalchemy/base.py:1068: SAWarning: The GenericFunction 'flatten' is already registered and is going to be overridden.
  functions.register_function("flatten", flatten)
[2024-07-25T18:29:40.418+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:29:40.425+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 1.736 seconds
[2024-07-25T18:30:11.236+0000] {processor.py:161} INFO - Started process (PID=4764) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:30:11.237+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T18:30:11.240+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:30:11.239+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:30:12.281+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:30:12.281+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/snowflake/sqlalchemy/base.py:1068: SAWarning: The GenericFunction 'flatten' is already registered and is going to be overridden.
  functions.register_function("flatten", flatten)
[2024-07-25T18:30:13.050+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:30:13.059+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 1.831 seconds
[2024-07-25T18:30:43.832+0000] {processor.py:161} INFO - Started process (PID=4833) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:30:43.840+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T18:30:43.845+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:30:43.845+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:30:44.937+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:30:44.937+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/snowflake/sqlalchemy/base.py:1068: SAWarning: The GenericFunction 'flatten' is already registered and is going to be overridden.
  functions.register_function("flatten", flatten)
[2024-07-25T18:30:45.670+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:30:45.679+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 1.853 seconds
[2024-07-25T18:31:16.469+0000] {processor.py:161} INFO - Started process (PID=4902) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:31:16.471+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T18:31:16.474+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:31:16.474+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:31:17.394+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:31:17.394+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/snowflake/sqlalchemy/base.py:1068: SAWarning: The GenericFunction 'flatten' is already registered and is going to be overridden.
  functions.register_function("flatten", flatten)
[2024-07-25T18:31:18.048+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:31:18.055+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 1.594 seconds
[2024-07-25T18:31:48.877+0000] {processor.py:161} INFO - Started process (PID=4971) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:31:48.879+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T18:31:48.883+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:31:48.883+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:31:49.938+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:31:49.938+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/snowflake/sqlalchemy/base.py:1068: SAWarning: The GenericFunction 'flatten' is already registered and is going to be overridden.
  functions.register_function("flatten", flatten)
[2024-07-25T18:31:50.601+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:31:50.609+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 1.743 seconds
[2024-07-25T18:32:21.298+0000] {processor.py:161} INFO - Started process (PID=5040) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:32:21.300+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T18:32:21.305+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:32:21.304+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:32:22.188+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:32:22.187+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/snowflake/sqlalchemy/base.py:1068: SAWarning: The GenericFunction 'flatten' is already registered and is going to be overridden.
  functions.register_function("flatten", flatten)
[2024-07-25T18:32:22.867+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:32:22.877+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 1.584 seconds
[2024-07-25T18:32:53.297+0000] {processor.py:161} INFO - Started process (PID=5112) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:32:53.298+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T18:32:53.301+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:32:53.300+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:32:54.495+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:32:54.494+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/snowflake/sqlalchemy/base.py:1068: SAWarning: The GenericFunction 'flatten' is already registered and is going to be overridden.
  functions.register_function("flatten", flatten)
[2024-07-25T18:32:55.270+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:32:55.282+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 1.992 seconds
[2024-07-25T18:33:36.110+0000] {processor.py:161} INFO - Started process (PID=31) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:33:36.111+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T18:33:36.113+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:33:36.113+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:33:38.642+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/sqlalchemy_redshift/commands.py:31 SyntaxWarning: invalid escape sequence '\-'
[2024-07-25T18:33:38.644+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/sqlalchemy_redshift/commands.py:33 SyntaxWarning: invalid escape sequence '\-'
[2024-07-25T18:33:39.907+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:33:39.906+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/snowflake/sqlalchemy/base.py:1068: SAWarning: The GenericFunction 'flatten' is already registered and is going to be overridden.
  functions.register_function("flatten", flatten)
[2024-07-25T18:33:40.671+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:33:40.678+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 4.570 seconds
[2024-07-25T18:34:11.641+0000] {processor.py:161} INFO - Started process (PID=150) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:34:11.642+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T18:34:11.643+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:34:11.643+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:34:12.620+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:34:12.619+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/snowflake/sqlalchemy/base.py:1068: SAWarning: The GenericFunction 'flatten' is already registered and is going to be overridden.
  functions.register_function("flatten", flatten)
[2024-07-25T18:34:13.258+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:34:13.264+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 1.629 seconds
[2024-07-25T18:34:43.983+0000] {processor.py:161} INFO - Started process (PID=222) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:34:43.984+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T18:34:43.986+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:34:43.986+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:34:44.918+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:34:44.918+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/snowflake/sqlalchemy/base.py:1068: SAWarning: The GenericFunction 'flatten' is already registered and is going to be overridden.
  functions.register_function("flatten", flatten)
[2024-07-25T18:34:45.511+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:34:45.516+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 1.538 seconds
[2024-07-25T18:35:16.140+0000] {processor.py:161} INFO - Started process (PID=291) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:35:16.141+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T18:35:16.143+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:35:16.143+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:35:17.069+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:35:17.069+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/snowflake/sqlalchemy/base.py:1068: SAWarning: The GenericFunction 'flatten' is already registered and is going to be overridden.
  functions.register_function("flatten", flatten)
[2024-07-25T18:35:17.698+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:35:17.704+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 1.571 seconds
[2024-07-25T18:35:48.237+0000] {processor.py:161} INFO - Started process (PID=360) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:35:48.238+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T18:35:48.240+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:35:48.240+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:35:49.213+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:35:49.213+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/snowflake/sqlalchemy/base.py:1068: SAWarning: The GenericFunction 'flatten' is already registered and is going to be overridden.
  functions.register_function("flatten", flatten)
[2024-07-25T18:35:49.890+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:35:49.899+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 1.665 seconds
[2024-07-25T18:36:19.936+0000] {processor.py:161} INFO - Started process (PID=429) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:36:19.937+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T18:36:19.938+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:36:19.938+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:36:20.917+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:36:20.917+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/snowflake/sqlalchemy/base.py:1068: SAWarning: The GenericFunction 'flatten' is already registered and is going to be overridden.
  functions.register_function("flatten", flatten)
[2024-07-25T18:36:21.637+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:36:21.646+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 1.716 seconds
[2024-07-25T18:36:52.431+0000] {processor.py:161} INFO - Started process (PID=498) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:36:52.432+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T18:36:52.434+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:36:52.434+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:36:53.425+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:36:53.425+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/snowflake/sqlalchemy/base.py:1068: SAWarning: The GenericFunction 'flatten' is already registered and is going to be overridden.
  functions.register_function("flatten", flatten)
[2024-07-25T18:36:54.048+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:36:54.056+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 1.631 seconds
[2024-07-25T18:37:24.196+0000] {processor.py:161} INFO - Started process (PID=567) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:37:24.198+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T18:37:24.202+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:37:24.202+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:37:25.299+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:37:25.299+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/snowflake/sqlalchemy/base.py:1068: SAWarning: The GenericFunction 'flatten' is already registered and is going to be overridden.
  functions.register_function("flatten", flatten)
[2024-07-25T18:37:25.922+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:37:25.934+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 1.757 seconds
[2024-07-25T18:37:31.935+0000] {processor.py:161} INFO - Started process (PID=583) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:37:31.936+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T18:37:31.937+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:37:31.937+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:37:32.848+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:37:32.848+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/snowflake/sqlalchemy/base.py:1068: SAWarning: The GenericFunction 'flatten' is already registered and is going to be overridden.
  functions.register_function("flatten", flatten)
[2024-07-25T18:37:33.467+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:37:33.467+0000] {warnings.py:112} WARNING - /opt/airflow/dags/great_expectations_dag.py:112: RemovedInAirflow3Warning: Param `schedule_interval` is deprecated and will be removed in a future release. Please use `schedule` instead. 
  with DAG(
[2024-07-25T18:37:33.468+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:37:33.468+0000] {warnings.py:112} WARNING - /opt/airflow/dags/great_expectations_dag.py:120: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `airflow.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  get_table_names = PostgresOperator(
[2024-07-25T18:37:33.469+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:37:33.469+0000] {warnings.py:112} WARNING - /opt/airflow/dags/great_expectations_dag.py:131: RemovedInAirflow3Warning: provide_context is deprecated as of 2.0 and is no longer required
  log_tables = PythonOperator(
[2024-07-25T18:37:33.470+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:37:33.469+0000] {warnings.py:112} WARNING - /opt/airflow/dags/great_expectations_dag.py:138: RemovedInAirflow3Warning: provide_context is deprecated as of 2.0 and is no longer required
  ge_check = PythonOperator(
[2024-07-25T18:37:33.470+0000] {processor.py:840} INFO - DAG(s) 'list_db_tables_with_ge' retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:37:33.515+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:37:33.515+0000] {override.py:1858} INFO - Created Permission View: can edit on DAG:list_db_tables_with_ge
[2024-07-25T18:37:33.519+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:37:33.519+0000] {override.py:1858} INFO - Created Permission View: can read on DAG:list_db_tables_with_ge
[2024-07-25T18:37:33.522+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:37:33.522+0000] {override.py:1858} INFO - Created Permission View: can delete on DAG:list_db_tables_with_ge
[2024-07-25T18:37:33.523+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:37:33.522+0000] {dag.py:3089} INFO - Sync 1 DAGs
[2024-07-25T18:37:33.527+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:37:33.527+0000] {dag.py:3111} INFO - Creating ORM DAG for list_db_tables_with_ge
[2024-07-25T18:37:33.528+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:37:33.528+0000] {dag.py:3947} INFO - Setting next_dagrun for list_db_tables_with_ge to None, run_after=None
[2024-07-25T18:37:33.535+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 1.604 seconds
[2024-07-25T18:38:03.603+0000] {processor.py:161} INFO - Started process (PID=652) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:38:03.604+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T18:38:03.608+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:38:03.607+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:38:04.706+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:38:04.706+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/snowflake/sqlalchemy/base.py:1068: SAWarning: The GenericFunction 'flatten' is already registered and is going to be overridden.
  functions.register_function("flatten", flatten)
[2024-07-25T18:38:05.322+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:38:05.322+0000] {warnings.py:112} WARNING - /opt/airflow/dags/great_expectations_dag.py:112: RemovedInAirflow3Warning: Param `schedule_interval` is deprecated and will be removed in a future release. Please use `schedule` instead. 
  with DAG(
[2024-07-25T18:38:05.323+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:38:05.322+0000] {warnings.py:112} WARNING - /opt/airflow/dags/great_expectations_dag.py:120: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `airflow.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  get_table_names = PostgresOperator(
[2024-07-25T18:38:05.323+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:38:05.323+0000] {warnings.py:112} WARNING - /opt/airflow/dags/great_expectations_dag.py:131: RemovedInAirflow3Warning: provide_context is deprecated as of 2.0 and is no longer required
  log_tables = PythonOperator(
[2024-07-25T18:38:05.324+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:38:05.324+0000] {warnings.py:112} WARNING - /opt/airflow/dags/great_expectations_dag.py:138: RemovedInAirflow3Warning: provide_context is deprecated as of 2.0 and is no longer required
  ge_check = PythonOperator(
[2024-07-25T18:38:05.324+0000] {processor.py:840} INFO - DAG(s) 'list_db_tables_with_ge' retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:38:05.334+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:38:05.334+0000] {dag.py:3089} INFO - Sync 1 DAGs
[2024-07-25T18:38:05.339+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:38:05.339+0000] {dag.py:3947} INFO - Setting next_dagrun for list_db_tables_with_ge to None, run_after=None
[2024-07-25T18:38:05.348+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 1.752 seconds
[2024-07-25T18:38:35.484+0000] {processor.py:161} INFO - Started process (PID=721) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:38:35.486+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T18:38:35.490+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:38:35.489+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:38:36.701+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:38:36.701+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/snowflake/sqlalchemy/base.py:1068: SAWarning: The GenericFunction 'flatten' is already registered and is going to be overridden.
  functions.register_function("flatten", flatten)
[2024-07-25T18:38:37.253+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:38:37.253+0000] {warnings.py:112} WARNING - /opt/airflow/dags/great_expectations_dag.py:112: RemovedInAirflow3Warning: Param `schedule_interval` is deprecated and will be removed in a future release. Please use `schedule` instead. 
  with DAG(
[2024-07-25T18:38:37.254+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:38:37.254+0000] {warnings.py:112} WARNING - /opt/airflow/dags/great_expectations_dag.py:120: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `airflow.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  get_table_names = PostgresOperator(
[2024-07-25T18:38:37.255+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:38:37.255+0000] {warnings.py:112} WARNING - /opt/airflow/dags/great_expectations_dag.py:131: RemovedInAirflow3Warning: provide_context is deprecated as of 2.0 and is no longer required
  log_tables = PythonOperator(
[2024-07-25T18:38:37.255+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:38:37.255+0000] {warnings.py:112} WARNING - /opt/airflow/dags/great_expectations_dag.py:138: RemovedInAirflow3Warning: provide_context is deprecated as of 2.0 and is no longer required
  ge_check = PythonOperator(
[2024-07-25T18:38:37.255+0000] {processor.py:840} INFO - DAG(s) 'list_db_tables_with_ge' retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:38:37.266+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:38:37.266+0000] {dag.py:3089} INFO - Sync 1 DAGs
[2024-07-25T18:38:37.375+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:38:37.375+0000] {dag.py:3947} INFO - Setting next_dagrun for list_db_tables_with_ge to None, run_after=None
[2024-07-25T18:38:37.385+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 1.911 seconds
[2024-07-25T18:39:07.469+0000] {processor.py:161} INFO - Started process (PID=790) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:39:07.478+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T18:39:07.482+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:39:07.481+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:39:08.532+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:39:08.532+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/snowflake/sqlalchemy/base.py:1068: SAWarning: The GenericFunction 'flatten' is already registered and is going to be overridden.
  functions.register_function("flatten", flatten)
[2024-07-25T18:39:09.054+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:39:09.054+0000] {warnings.py:112} WARNING - /opt/airflow/dags/great_expectations_dag.py:112: RemovedInAirflow3Warning: Param `schedule_interval` is deprecated and will be removed in a future release. Please use `schedule` instead. 
  with DAG(
[2024-07-25T18:39:09.055+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:39:09.055+0000] {warnings.py:112} WARNING - /opt/airflow/dags/great_expectations_dag.py:120: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `airflow.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  get_table_names = PostgresOperator(
[2024-07-25T18:39:09.055+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:39:09.055+0000] {warnings.py:112} WARNING - /opt/airflow/dags/great_expectations_dag.py:131: RemovedInAirflow3Warning: provide_context is deprecated as of 2.0 and is no longer required
  log_tables = PythonOperator(
[2024-07-25T18:39:09.056+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:39:09.056+0000] {warnings.py:112} WARNING - /opt/airflow/dags/great_expectations_dag.py:138: RemovedInAirflow3Warning: provide_context is deprecated as of 2.0 and is no longer required
  ge_check = PythonOperator(
[2024-07-25T18:39:09.056+0000] {processor.py:840} INFO - DAG(s) 'list_db_tables_with_ge' retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:39:09.065+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:39:09.065+0000] {dag.py:3089} INFO - Sync 1 DAGs
[2024-07-25T18:39:09.171+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:39:09.170+0000] {dag.py:3947} INFO - Setting next_dagrun for list_db_tables_with_ge to None, run_after=None
[2024-07-25T18:39:09.179+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 1.717 seconds
[2024-07-25T18:39:39.892+0000] {processor.py:161} INFO - Started process (PID=859) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:39:39.894+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T18:39:39.899+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:39:39.899+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:39:41.111+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:39:41.111+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/snowflake/sqlalchemy/base.py:1068: SAWarning: The GenericFunction 'flatten' is already registered and is going to be overridden.
  functions.register_function("flatten", flatten)
[2024-07-25T18:39:41.881+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:39:41.881+0000] {warnings.py:112} WARNING - /opt/airflow/dags/great_expectations_dag.py:112: RemovedInAirflow3Warning: Param `schedule_interval` is deprecated and will be removed in a future release. Please use `schedule` instead. 
  with DAG(
[2024-07-25T18:39:41.883+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:39:41.882+0000] {warnings.py:112} WARNING - /opt/airflow/dags/great_expectations_dag.py:120: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `airflow.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  get_table_names = PostgresOperator(
[2024-07-25T18:39:41.886+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:39:41.886+0000] {warnings.py:112} WARNING - /opt/airflow/dags/great_expectations_dag.py:131: RemovedInAirflow3Warning: provide_context is deprecated as of 2.0 and is no longer required
  log_tables = PythonOperator(
[2024-07-25T18:39:41.887+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:39:41.887+0000] {warnings.py:112} WARNING - /opt/airflow/dags/great_expectations_dag.py:138: RemovedInAirflow3Warning: provide_context is deprecated as of 2.0 and is no longer required
  ge_check = PythonOperator(
[2024-07-25T18:39:41.888+0000] {processor.py:840} INFO - DAG(s) 'list_db_tables_with_ge' retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:39:41.902+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:39:41.902+0000] {dag.py:3089} INFO - Sync 1 DAGs
[2024-07-25T18:39:41.909+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:39:41.908+0000] {dag.py:3947} INFO - Setting next_dagrun for list_db_tables_with_ge to None, run_after=None
[2024-07-25T18:39:42.086+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 2.207 seconds
[2024-07-25T18:40:12.172+0000] {processor.py:161} INFO - Started process (PID=929) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:40:12.173+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T18:40:12.174+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:40:12.174+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:40:13.314+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:40:13.314+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/snowflake/sqlalchemy/base.py:1068: SAWarning: The GenericFunction 'flatten' is already registered and is going to be overridden.
  functions.register_function("flatten", flatten)
[2024-07-25T18:40:14.003+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:40:14.003+0000] {warnings.py:112} WARNING - /opt/airflow/dags/great_expectations_dag.py:112: RemovedInAirflow3Warning: Param `schedule_interval` is deprecated and will be removed in a future release. Please use `schedule` instead. 
  with DAG(
[2024-07-25T18:40:14.004+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:40:14.004+0000] {warnings.py:112} WARNING - /opt/airflow/dags/great_expectations_dag.py:120: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `airflow.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  get_table_names = PostgresOperator(
[2024-07-25T18:40:14.005+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:40:14.005+0000] {warnings.py:112} WARNING - /opt/airflow/dags/great_expectations_dag.py:131: RemovedInAirflow3Warning: provide_context is deprecated as of 2.0 and is no longer required
  log_tables = PythonOperator(
[2024-07-25T18:40:14.005+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:40:14.005+0000] {warnings.py:112} WARNING - /opt/airflow/dags/great_expectations_dag.py:138: RemovedInAirflow3Warning: provide_context is deprecated as of 2.0 and is no longer required
  ge_check = PythonOperator(
[2024-07-25T18:40:14.006+0000] {processor.py:840} INFO - DAG(s) 'list_db_tables_with_ge' retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:40:14.015+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:40:14.015+0000] {dag.py:3089} INFO - Sync 1 DAGs
[2024-07-25T18:40:14.021+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:40:14.020+0000] {dag.py:3947} INFO - Setting next_dagrun for list_db_tables_with_ge to None, run_after=None
[2024-07-25T18:40:14.136+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 1.966 seconds
[2024-07-25T18:40:44.729+0000] {processor.py:161} INFO - Started process (PID=1005) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:40:44.730+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T18:40:44.731+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:40:44.731+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:40:46.034+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:40:46.034+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/snowflake/sqlalchemy/base.py:1068: SAWarning: The GenericFunction 'flatten' is already registered and is going to be overridden.
  functions.register_function("flatten", flatten)
[2024-07-25T18:40:46.848+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:40:46.847+0000] {warnings.py:112} WARNING - /opt/airflow/dags/great_expectations_dag.py:112: RemovedInAirflow3Warning: Param `schedule_interval` is deprecated and will be removed in a future release. Please use `schedule` instead. 
  with DAG(
[2024-07-25T18:40:46.848+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:40:46.848+0000] {warnings.py:112} WARNING - /opt/airflow/dags/great_expectations_dag.py:120: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `airflow.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  get_table_names = PostgresOperator(
[2024-07-25T18:40:46.849+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:40:46.849+0000] {warnings.py:112} WARNING - /opt/airflow/dags/great_expectations_dag.py:131: RemovedInAirflow3Warning: provide_context is deprecated as of 2.0 and is no longer required
  log_tables = PythonOperator(
[2024-07-25T18:40:46.849+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:40:46.849+0000] {warnings.py:112} WARNING - /opt/airflow/dags/great_expectations_dag.py:138: RemovedInAirflow3Warning: provide_context is deprecated as of 2.0 and is no longer required
  ge_check = PythonOperator(
[2024-07-25T18:40:46.850+0000] {processor.py:840} INFO - DAG(s) 'list_db_tables_with_ge' retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:40:46.859+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:40:46.859+0000] {dag.py:3089} INFO - Sync 1 DAGs
[2024-07-25T18:40:46.865+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:40:46.865+0000] {dag.py:3947} INFO - Setting next_dagrun for list_db_tables_with_ge to None, run_after=None
[2024-07-25T18:40:46.874+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 2.148 seconds
[2024-07-25T18:41:16.909+0000] {processor.py:161} INFO - Started process (PID=1089) to work on /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:41:16.910+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_dag.py for tasks to queue
[2024-07-25T18:41:16.911+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:41:16.910+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:41:17.994+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:41:17.994+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/snowflake/sqlalchemy/base.py:1068: SAWarning: The GenericFunction 'flatten' is already registered and is going to be overridden.
  functions.register_function("flatten", flatten)
[2024-07-25T18:41:18.631+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:41:18.631+0000] {warnings.py:112} WARNING - /opt/airflow/dags/great_expectations_dag.py:112: RemovedInAirflow3Warning: Param `schedule_interval` is deprecated and will be removed in a future release. Please use `schedule` instead. 
  with DAG(
[2024-07-25T18:41:18.632+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:41:18.632+0000] {warnings.py:112} WARNING - /opt/airflow/dags/great_expectations_dag.py:120: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `airflow.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  get_table_names = PostgresOperator(
[2024-07-25T18:41:18.633+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:41:18.633+0000] {warnings.py:112} WARNING - /opt/airflow/dags/great_expectations_dag.py:131: RemovedInAirflow3Warning: provide_context is deprecated as of 2.0 and is no longer required
  log_tables = PythonOperator(
[2024-07-25T18:41:18.633+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:41:18.633+0000] {warnings.py:112} WARNING - /opt/airflow/dags/great_expectations_dag.py:138: RemovedInAirflow3Warning: provide_context is deprecated as of 2.0 and is no longer required
  ge_check = PythonOperator(
[2024-07-25T18:41:18.634+0000] {processor.py:840} INFO - DAG(s) 'list_db_tables_with_ge' retrieved from /opt/airflow/dags/great_expectations_dag.py
[2024-07-25T18:41:18.645+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:41:18.645+0000] {dag.py:3089} INFO - Sync 1 DAGs
[2024-07-25T18:41:18.651+0000] {logging_mixin.py:188} INFO - [2024-07-25T18:41:18.651+0000] {dag.py:3947} INFO - Setting next_dagrun for list_db_tables_with_ge to None, run_after=None
[2024-07-25T18:41:18.777+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_dag.py took 1.871 seconds
